/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/Box.vue')['default']
    FileInput: typeof import('./src/atomic/FileInput.vue')['default']
    InferenceProfile: typeof import('./src/components/InferenceProfile.vue')['default']
    LiveVideoSettings: typeof import('./src/components/LiveVideoSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleButton: typeof import('./src/components/SimpleButton.vue')['default']
    TextInput: typeof import('./src/atomic/TextInput.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    ToggleButton: typeof import('./src/components/ToggleButton.vue')['default']
    VideoSource: typeof import('./src/components/VideoSource.vue')['default']
    ViewInterface: typeof import('./src/components/ViewInterface.vue')['default']
  }
}
